
[platformio]
default_envs = TRACKLINK-V3

; Common configuration for all ESP32 boards
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps =

;------------------------------------------------------------------------------------------------------------------------
; TRACKLINK board - Elecrow latest version
[env:TRACKLINK-V3]
board = lolin_s3_mini
board_build.partitions = huge_app.csv

build_flags = 	
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=5
	; Driver pins
	-D DRV_MA1=13
	-D DRV_MA2=14
	-D DRV_MB1=15
	-D DRV_MB2=16
	-D DRV_BEMF_A=4	
	-D DRV_BEMF_B=5
	-D DRV_EN=12
	; Led pins
	-D L1=6
	-D L2=7
	-D L3=8
	-D L4=9
	-D L5=10
	-D L6=11
	;-D LED_BUILTIN=42	
	; Servo pins
	-D S1=1
	; I2S pins (MAX98357)
	-D I2S_LRCLK=17
	-D I2S_BCLK=18
	-D I2S_DIN=21
	-D I2S_SD_MODE=47	
	; Boot button
	-D BOOT=0
	; Power pins
	-D PWR_EN=33	; set high to enable board
	-D PWR_BTN=48	; Input pin to detect power button press
	-D CHRG_SENS=34	; Input pin to detect USB power
	; Voltsense
	-D VSENS=2
	-D VSCALE=1.8
	-D VOFFSET=-0.2	
	; PWM settings
	-D LED_FREQ=8000
	-D LED_RES=10
	-D DRV_FREQ=24000
	-D DRV_RES=8

;========================================================================================================================
;----PREVIOUSLY USED BOARDS : ONLY FOR REFERENCE PURPOSES----------------------------------------------------------------
;========================================================================================================================
; TRACKLINK board
[env:TRACKLINK-V1]
board = adafruit_feather_esp32s3_nopsram

build_flags = 	
	; Driver pins
	-D DRV_MA1=12
	-D DRV_MA2=13
	-D DRV_MB1=14
	-D DRV_MB2=15
	-D DRV_EN=11	
	; Led pins
	-D L1=5
	-D L2=6
	-D L3=7
	-D L4=8
	-D L5=9
	-D L6=10
	-D LED_BUILTIN=48	
	; Servo pins
	-D S1=1
	-D S2=2	
	; I2S pins (MAX98357)
	-D I2S_LRCLK=16
	-D I2S_BCLK=17
	-D I2S_DIN=18
	-D I2S_SD_MODE=21	
	; Boot button
	-D BOOT=0
	; Voltsense
	-D VSENS=4
	-D VSCALE=4.2	
	; PWM settings
	-D LED_FREQ=8000
	-D LED_RES=10
	-D DRV_FREQ=24000
	-D DRV_RES=8