
[platformio]
default_envs = RC_Truck
src_dir = RC_Truck/src

; Common configuration for all ESP32 boards
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 2000000
extra_scripts = pre:scripts/gen_boards_header.py
lib_deps =
    ESP32_PWM_Fusion=symlink:///home/sun/Filelink/Arduino/libraries/ESP32_PWM_Fusion
    bblanchon/ArduinoJson @ ^7.0.4
lib_extra_dirs = .

board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

;------------------------------------------------------------------------------------------------------------------------
; RC Truck Controller
[env:RC_Truck]
board = esp32-s3-devkitc-1
board_build.partitions = huge_app.csv
board_build.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINOJSON_ENABLE_COMMENTS=1
	-D RC_TRUCK
	-I common
	-I boards
	; Boot button
	-D BOOT=0
	; Voltsense
	-D VSCALE=1.8
	-D VOFFSET=-0.2	
	; PWM settings
	-D LED_FREQ=8000
	-D LED_RES=10
	-D DRV_FREQ=24000
	-D DRV_RES=8

;------------------------------------------------------------------------------------------------------------------------
; RC Locomotive Controller
[env:RC_Loco]
board = esp32-s3-devkitc-1
board_build.partitions = huge_app.csv
board_build.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINOJSON_ENABLE_COMMENTS=1
	-D RC_LOCO
	-I common
	-I boards
	; Boot button
	-D BOOT=0
	; Voltsense
	-D VSCALE=1.8
	-D VOFFSET=-0.2	
	; PWM settings
	-D LED_FREQ=8000
	-D LED_RES=10
	-D DRV_FREQ=24000
	-D DRV_RES=8

;========================================================================================================================
;----PREVIOUSLY USED BOARDS : ONLY FOR REFERENCE PURPOSES----------------------------------------------------------------
;========================================================================================================================
