// boards/boards.h
// Umbrella header to include all board files conditionally based on the defined board name
// AUTO-GENERATED by gen_boards_header.py - DO NOT EDIT MANUALLY

#pragma once

#ifdef TRACKLINK_V3
#include "TRACKLINK_V3.h"
#endif
