"""
gen_boards_header.py
PlatformIO script to auto-generate src/boards/boards.h
from all *.h files in src/boards/ (excluding boards.h itself).
"""
import os
import glob

try:
    from SCons.Script import Import
    Import("env")
    PROJECT_DIR = env["PROJECT_DIR"]
except Exception:
    PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

def generate_boards_header(source, target, env):
    project_dir = env["PROJECT_DIR"]
    boards_dir = os.path.join(project_dir, "boards")
    boards_h = os.path.join(boards_dir, "boards.h")

    # Find all .h files in boards_dir, excluding boards.h
    board_files = sorted(glob.glob(os.path.join(boards_dir, "*.h")))
    board_files = [f for f in board_files if os.path.basename(f) != "boards.h"]

    # Generate content
    lines = [
        "// boards/boards.h",
        "// Umbrella header to include all board files conditionally based on the defined board name",
        "// AUTO-GENERATED by gen_boards_header.py - DO NOT EDIT MANUALLY",
        "",
        "#pragma once",
        "",
    ]

    for board_file in board_files:
        basename = os.path.basename(board_file)
        board_name = basename.replace(".h", "")
        lines.append(f"#ifdef {board_name}")
        lines.append(f'#include "{basename}"')
        lines.append("#endif")
        lines.append("")

    # Write boards.h
    with open(boards_h, "w") as f:
        f.write("\n".join(lines))

    board_names = [os.path.basename(f).replace(".h", "") for f in board_files]
    if board_names:
        print(f"[gen_boards_header] Updated boards.h with {len(board_names)} board(s): {', '.join(board_names)}")
    else:
        print("[gen_boards_header] WARNING: No board headers found in src/boards/")

# Execute immediately when script is loaded
project_dir = PROJECT_DIR
boards_dir = os.path.join(project_dir, "boards")
boards_h = os.path.join(boards_dir, "boards.h")

# Find all .h files in boards_dir, excluding boards.h
board_files = sorted(glob.glob(os.path.join(boards_dir, "*.h")))
board_files = [f for f in board_files if os.path.basename(f) != "boards.h"]

# Generate content
lines = [
    "// boards/boards.h",
    "// Umbrella header to include all board files conditionally based on the defined board name",
    "// AUTO-GENERATED by gen_boards_header.py - DO NOT EDIT MANUALLY",
    "",
    "#pragma once",
    "",
]

for board_file in board_files:
    basename = os.path.basename(board_file)
    board_name = basename.replace(".h", "")
    lines.append(f"#ifdef {board_name}")
    lines.append(f'#include "{basename}"')
    lines.append("#endif")
    lines.append("")

# Write boards.h
with open(boards_h, "w") as f:
    f.write("\n".join(lines))

board_names = [os.path.basename(f).replace(".h", "") for f in board_files]
if board_names:
    print(f"[gen_boards_header] Updated boards.h with {len(board_names)} board(s): {', '.join(board_names)}")
else:
    print("[gen_boards_header] WARNING: No board headers found in src/boards/")
